In [215]:
import random as rand
import numpy as np

In [251]:
basketSize = 10
solutions = 100


In [252]:
# Generate initial Solutions

population = np.random.randint(0,2, (solutions,basketSize))
# population

In [253]:
# Create Objects and Solution Containers
limit = {}
value = {}
basket = {}

def createItem(name, lim, val):
    global limit
    global value
    global basket

    limit[name] = lim
    value[name] = val
    basket[name] = int()

createItem('Apple', 50, 5)
createItem('Orange', 60, 4)
createItem('Kiwi', 40, 7)
createItem('Watermelon', 200, 9)
createItem('Grapes', 10, 8)
createItem('Papaya', 150, 1)
createItem('Pear', 55, 10)
createItem('Banana', 70, 11)
createItem('Avocado', 45, 12)
createItem('Dragon Fruit', 100, 4)


In [254]:
# Fitness Function
def getFitness():
    global population
    l = list(limit.values()) * population
    v = list(value.values()) * population
    return np.where(np.sum(l, axis = 1) <= 400, 1, 0) * np.sum(v, axis = 1)
    
# getFitness()

In [255]:
# Selection Function
def select(pop,fit):
    ix = np.random.choice(solutions, size = solutions, replace=True, p = fit/fit.sum())
    return pop[ix]


In [256]:
# Crossover Function
def crossOver(parent, pop):
    if np.random.rand() < 0.8:
        mother = np.random.randint(0,solutions, size =1)
        crossPoint = np.random.randint(0,2,size =basketSize).astype(bool)
        parent[crossPoint] = pop[mother,crossPoint]
    return parent
    

In [278]:
# Mutation Function 
def mutate(solution):
    for point in range(basketSize):
        if np.random.rand() < 0.003:
            if solution[point] == 1:
                solution[point] = 0
            else:
                solution[point] = 1
    return solution

In [279]:
# Main run
basketSize = 10
solutions = 300

population = np.random.randint(0,2, (solutions,basketSize))

generations = 300
log = {}

for i in range(generations):
    fit = getFitness()
    population = select(population, fit)
    log[i] = np.average(fit)
    
    for parent in population:
        popCopy = population.copy()
        child = crossOver(parent, popCopy)
        child = mutate(child)
        parent[:] = child
    
    # print(i)
    # print(population, np.average(fit))

In [280]:
log

{0: 15.33,
 1: 28.75,
 2: 30.84,
 3: 32.336666666666666,
 4: 34.98,
 5: 37.73,
 6: 41.27,
 7: 44.5,
 8: 45.29666666666667,
 9: 48.15,
 10: 49.096666666666664,
 11: 49.3,
 12: 49.72,
 13: 51.19,
 14: 51.47666666666667,
 15: 51.44,
 16: 51.50333333333333,
 17: 51.266666666666666,
 18: 50.85,
 19: 52.03,
 20: 52.41,
 21: 52.096666666666664,
 22: 53.28666666666667,
 23: 52.60333333333333,
 24: 54.04333333333334,
 25: 53.24333333333333,
 26: 54.66,
 27: 54.25333333333333,
 28: 54.05,
 29: 53.46333333333333,
 30: 54.29,
 31: 54.65,
 32: 53.45,
 33: 54.123333333333335,
 34: 54.27,
 35: 55.346666666666664,
 36: 54.513333333333335,
 37: 55.02,
 38: 55.33,
 39: 54.873333333333335,
 40: 55.223333333333336,
 41: 55.446666666666665,
 42: 55.946666666666665,
 43: 55.17,
 44: 56.126666666666665,
 45: 55.95,
 46: 55.91,
 47: 56.4,
 48: 55.07,
 49: 55.77333333333333,
 50: 55.416666666666664,
 51: 55.39333333333333,
 52: 54.85666666666667,
 53: 55.14333333333333,
 54: 54.95,
 55: 54.96666666666667,
 56:

In [277]:
list(population)

[array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1]),
 array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1]),
 array([1, 0, 0, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0]),
 array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0]),
 array([0, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([0, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([0, 1, 1, 0, 1, 0, 1, 1, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1]),
 array([1, 0, 1, 1, 0, 0, 1, 1, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),


In [209]:
np.random.randint(0,2,size =basketSize).astype(bool)

array([ True, False,  True, False,  True,  True,  True, False,  True,
        True])

In [208]:
np.random.randint(0,solutions, size =1)

array([2])