In [215]:
import random as rand
import numpy as np

In [251]:
basketSize = 10
solutions = 100


In [252]:
# Generate initial Solutions

population = np.random.randint(0,2, (solutions,basketSize))
# population

In [253]:
# Create Objects and Solution Containers
limit = {}
value = {}
basket = {}

def createItem(name, lim, val):
    global limit
    global value
    global basket

    limit[name] = lim
    value[name] = val
    basket[name] = int()

createItem('Apple', 50, 5)
createItem('Orange', 60, 4)
createItem('Kiwi', 40, 7)
createItem('Watermelon', 200, 9)
createItem('Grapes', 10, 8)
createItem('Papaya', 150, 1)
createItem('Pear', 55, 10)
createItem('Banana', 70, 11)
createItem('Avocado', 45, 12)
createItem('Dragon Fruit', 100, 4)


In [254]:
# Fitness Function
def getFitness():
    global population
    l = list(limit.values()) * population
    v = list(value.values()) * population
    return np.where(np.sum(l, axis = 1) <= 400, 1, 0) * np.sum(v, axis = 1)
    
# getFitness()

In [255]:
# Selection Function
def select(pop,fit):
    ix = np.random.choice(solutions, size = solutions, replace=True, p = fit/fit.sum())
    return pop[ix]


In [256]:
# Crossover Function
def crossOver(parent, pop):
    if np.random.rand() < 0.8:
        mother = np.random.randint(0,solutions, size =1)
        crossPoint = np.random.randint(0,2,size =basketSize).astype(bool)
        parent[crossPoint] = pop[mother,crossPoint]
    return parent
    

In [278]:
# Mutation Function 
def mutate(solution):
    for point in range(basketSize):
        if np.random.rand() < 0.003:
            if solution[point] == 1:
                solution[point] = 0
            else:
                solution[point] = 1
    return solution

In [283]:
# Main run
basketSize = 10
solutions = 300

population = np.random.randint(0,2, (solutions,basketSize))

generations = 500
log = {}

for i in range(generations):
    fit = getFitness()
    population = select(population, fit)
    log[i] = round(np.average(fit),2)
    
    for parent in population:
        popCopy = population.copy()
        child = crossOver(parent, popCopy)
        child = mutate(child)
        parent[:] = child
    
    # print(i)
    # print(population, np.average(fit))

In [284]:
log

{0: 13.63,
 1: 25.26,
 2: 25.7,
 3: 28.76,
 4: 30.4,
 5: 34.84,
 6: 36.85,
 7: 40.43,
 8: 41.28,
 9: 40.44,
 10: 42.94,
 11: 43.53,
 12: 46.56,
 13: 47.62,
 14: 47.6,
 15: 50.2,
 16: 49.52,
 17: 51.06,
 18: 50.95,
 19: 52.44,
 20: 51.75,
 21: 52.47,
 22: 53.0,
 23: 53.26,
 24: 53.33,
 25: 53.61,
 26: 53.19,
 27: 53.76,
 28: 54.09,
 29: 55.01,
 30: 54.94,
 31: 54.71,
 32: 54.86,
 33: 54.57,
 34: 53.79,
 35: 53.93,
 36: 54.4,
 37: 53.97,
 38: 55.45,
 39: 55.22,
 40: 55.13,
 41: 55.26,
 42: 54.3,
 43: 54.63,
 44: 54.24,
 45: 54.03,
 46: 54.06,
 47: 54.03,
 48: 54.39,
 49: 54.86,
 50: 55.14,
 51: 54.89,
 52: 55.37,
 53: 55.6,
 54: 53.97,
 55: 55.37,
 56: 55.04,
 57: 54.79,
 58: 55.12,
 59: 54.04,
 60: 54.34,
 61: 54.32,
 62: 54.02,
 63: 54.27,
 64: 54.63,
 65: 54.72,
 66: 54.81,
 67: 53.87,
 68: 53.87,
 69: 53.53,
 70: 53.49,
 71: 53.63,
 72: 54.47,
 73: 54.61,
 74: 53.07,
 75: 53.14,
 76: 53.23,
 77: 54.02,
 78: 53.96,
 79: 54.49,
 80: 53.45,
 81: 53.54,
 82: 53.59,
 83: 53.27,
 84: 52.97

In [277]:
list(population)

[array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1]),
 array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1]),
 array([1, 0, 0, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0]),
 array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0]),
 array([0, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([0, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([0, 1, 1, 0, 1, 0, 1, 1, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1]),
 array([1, 0, 1, 1, 0, 0, 1, 1, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
